import { Product, Category, HeroSlide } from "./types";

export const heroSlides: HeroSlide[] = [
  {
    id: "pesach",
    title: "מתנות לפסח",
    subtitle: "הפתיעו את המשפחה עם מתנות מעוצבות לשולחן החג",
    cta: "למוצרי פסח",
    href: "/category?cat=holidays",
    bgGradient: "from-sky/40 to-green-soft/30",
    emoji: "🍷",
  },
  {
    id: "teachers",
    title: "מתנות למורים",
    subtitle: "תודה מהלב - מתנות מרגשות לסוף שנת הלימודים",
    cta: "למתנות סוף שנה",
    href: "/category?cat=end-of-year",
    bgGradient: "from-pink/30 to-lavender/30",
    emoji: "🎓",
  },
  {
    id: "personal",
    title: "מתנות בעיצוב אישי",
    subtitle: "הפכו כל מתנה לייחודית עם הקדשה ועיצוב אישי",
    cta: "עצב מתנה עכשיו",
    href: "/category?type=custom",
    bgGradient: "from-orange-soft/30 to-yellow-soft/30",
    emoji: "🎁",
  },
  {
    id: "birthday",
    title: "מתנות ליום הולדת",
    subtitle: "מתנות מקוריות ומיוחדות ליום ההולדת שלהם",
    cta: "למתנות יום הולדת",
    href: "/category?cat=birthday",
    bgGradient: "from-purple-soft/30 to-pink/20",
    emoji: "🎂",
  },
];

export const categories: Category[] = [
  { id: "1", name: "חגים", image: "/images/categories/holidays.jpg", slug: "holidays" },
  { id: "2", name: "סוף שנה", image: "/images/categories/end-of-year.jpg", slug: "end-of-year" },
  { id: "3", name: "יודאיקה", image: "/images/categories/judaica.jpg", slug: "judaica" },
  { id: "4", name: "גיוס", image: "/images/categories/army.jpg", slug: "army" },
  { id: "5", name: "ימי הולדת", image: "/images/categories/birthday.jpg", slug: "birthday" },
  { id: "6", name: "בלונים", image: "/images/categories/balloons.jpg", slug: "balloons" },
  { id: "7", name: "מזכרות", image: "/images/categories/souvenirs.jpg", slug: "souvenirs" },
  { id: "8", name: "מארזים", image: "/images/categories/packages.jpg", slug: "packages" },
];

export const products: Product[] = [
  {
    id: "1",
    name: "צלחת לפסח בעיצוב אישי",
    price: 89,
    image: "/images/products/pesach-plate.jpg",
    category: "holidays",
    type: "custom",
    description: "צלחת מעוצבת לשולחן החג עם הקדשה אישית",
  },
  {
    id: "2",
    name: "מתנה למורה - כוס עם הקדשה",
    price: 65,
    image: "/images/products/teacher-cup.jpg",
    category: "end-of-year",
    type: "custom",
    description: "כוס מעוצבת עם הקדשה אישית למורה האהובה",
  },
  {
    id: "3",
    name: "מזוזה מעוצבת",
    price: 120,
    image: "/images/products/mezuzah.jpg",
    category: "judaica",
    type: "regular",
    description: "מזוזה מעוצבת בסגנון מודרני ואלגנטי",
  },
  {
    id: "4",
    name: "מארז גיוס מפנק",
    price: 199,
    image: "/images/products/army-kit.jpg",
    category: "army",
    type: "regular",
    description: "מארז מתנה מושלם לחייל/ת טרי/ה",
  },
  {
    id: "5",
    name: "באנר יום הולדת בהתאמה אישית",
    price: 45,
    image: "/images/products/birthday-banner.jpg",
    category: "birthday",
    type: "custom",
    description: "באנר מעוצב עם שם וגיל ליום ההולדת",
  },
  {
    id: "6",
    name: "זר בלונים חגיגי",
    price: 85,
    image: "/images/products/balloons.jpg",
    category: "balloons",
    type: "regular",
    description: "זר בלונים צבעוני ומרשים לכל אירוע",
  },
  {
    id: "7",
    name: "מגנט מזכרת בעיצוב אישי",
    price: 35,
    image: "/images/products/magnet.jpg",
    category: "souvenirs",
    type: "custom",
    description: "מגנט מעוצב עם תמונה והקדשה אישית",
  },
  {
    id: "8",
    name: "מארז מתנה פרימיום",
    price: 250,
    image: "/images/products/premium-package.jpg",
    category: "packages",
    type: "regular",
    description: "מארז מתנה מפנק הכולל מגוון מוצרים מעוצבים",
  },
];
